### PR TITLE
Remove insult from No Shaders description

### PR DESCRIPTION
**Pull request by slideglide**
I can't read the fucking manual if the fucking manual actively insults me, so this pull request fixes that

### CODE REVIEW

**Comment by Chameleon-Coder** [comment]
I think the insult just adds some humor to it

**Comment by TheSillyDoggo** [comment]
stop fucking trying to get into the contributors section on the github

**Comment by ItsJaid** [comment]
hes already there though... you've already merged one pr from him Screenshot_20241219-003701~2

**Comment by VictorGabrielGames** [comment]
sup justadude64

**Comment by TheSillyDoggo** [comment]
> > stop fucking trying to get into the contributors section on the github
> 
> are you stupid? im already in the contributors section

YOURE FUCKING STUPID

**Comment by MysticAx0lotl** [comment]
> YOURE FUCKING STUPID

Inspiring words, thank you doggo 😇

**Comment by TheSillyDoggo** [comment]
oh not you

**Comment by JustADude64** [comment]
> > > stop fucking trying to get into the contributors section on the github
> > 
> > 
> > are you stupid? im already in the contributors section
> 
> YOURE FUCKING STUPID

Guys let's quit it with the insults
Pft... Get it? "Remove insult from No Shaders description"?

"Insult"? Tee hee 🤑🤑🤑

**Comment by zMidair** [comment]
> > > > stop fucking trying to get into the contributors section on the github
> > > 
> > > 
> > > are you stupid? im already in the contributors section
> > 
> > 
> > YOURE FUCKING STUPID
> 
> Guys let's quit it with the insults Pft... Get it? "Remove insult from No Shaders description"?
> 
> "Insult"? Tee hee 🤑🤑🤑

wtf 😔🔫

**Pull request closed without merging**
